AWSTemplateFormatVersion: "2010-09-09"
Description: Sample template showing the usage of VS::Lightsail::Instance

Resources:
  LightsailInstance:
    Type: VS::Lightsail::Instance
    Properties:
        AvailabilityZone: us-east-1a
        BundleId: nano_2_0
        BlueprintId: amazon_linux
